name: CI Infra as Code
on:
  [workflow_dispatch, push]
concurrency: ci-${{ github.ref }}
jobs:

  trivy:
    name: Run Trivy (Iac and fs mode)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm install

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'


  sonarQube:
  on:
    push:
      branches:
        - master
    pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



  deploy:
    name: deploy Angular App 🚀
    needs: [trivy]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the thing
        run: |
          echo Deploying your Angular App🚀